In [26]:
import pandas as pd

In [27]:
df = pd.read_csv('data/pokemon.csv')

In [36]:
df.head(n=30)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False
15,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False
18,15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
24,19,Rattata,Normal,NaN,253,30,56,35,25,35,72,1,False
25,20,Raticate,Normal,NaN,413,55,81,60,50,70,97,1,False
26,21,Spearow,Normal,Flying,262,40,60,30,31,31,70,1,False
27,22,Fearow,Normal,Flying,442,65,90,65,61,61,100,1,False
28,23,Ekans,Poison,NaN,288,35,60,44,40,54,55,1,False
29,24,Arbok,Poison,NaN,438,60,85,69,65,79,80,1,False

In [29]:
type(df)

pandas.core.frame.DataFrame

In [43]:
df['Type 2']

0      Poison
1      Poison
2      Poison
3      Poison
4         NaN
        ...
795     Fairy
796     Fairy
797     Ghost
798      Dark
799     Water
Name: Type 2, Length: 800, dtype: object

In [37]:
df.shape

(800, 13)

In [31]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [8]:
type(df.columns)

pandas.core.indexes.base.Index

In [9]:
df.dtypes

abilities             object
against_bug          float64
against_dark         float64
against_dragon       float64
against_electric     float64
against_fairy        float64
against_fight        float64
against_fire         float64
against_flying       float64
against_ghost        float64
against_grass        float64
against_ground       float64
against_ice          float64
against_normal       float64
against_poison       float64
against_psychic      float64
against_rock         float64
against_steel        float64
against_water        float64
attack                 int64
base_egg_steps         int64
base_happiness         int64
base_total             int64
capture_rate          object
classfication         object
defense                int64
experience_growth      int64
height_m             float64
hp                     int64
japanese_name         object
name                  object
percentage_male      float64
pokedex_number         int64
sp_attack              int64
sp_defense             int64
speed                  int64
type1                 object
type2                 object
weight_kg            float64
generation             int64
is_legendary           int64
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 41 columns):
abilities            801 non-null object
against_bug          801 non-null float64
against_dark         801 non-null float64
against_dragon       801 non-null float64
against_electric     801 non-null float64
against_fairy        801 non-null float64
against_fight        801 non-null float64
against_fire         801 non-null float64
against_flying       801 non-null float64
against_ghost        801 non-null float64
against_grass        801 non-null float64
against_ground       801 non-null float64
against_ice          801 non-null float64
against_normal       801 non-null float64
against_poison       801 non-null float64
against_psychic      801 non-null float64
against_rock         801 non-null float64
against_steel        801 non-null float64
against_water        801 non-null float64
attack               801 non-null int64
base_egg_steps       801 non-null int64
base_happiness       801 non-null int64
base_total           801 non-null int64
capture_rate         801 non-null object
classfication        801 non-null object
defense              801 non-null int64
experience_growth    801 non-null int64
height_m             781 non-null float64
hp                   801 non-null int64
japanese_name        801 non-null object
name                 801 non-null object
percentage_male      703 non-null float64
pokedex_number       801 non-null int64
sp_attack            801 non-null int64
sp_defense           801 non-null int64
speed                801 non-null int64
type1                801 non-null object
type2                417 non-null object
weight_kg            781 non-null float64
generation           801 non-null int64
is_legendary         801 non-null int64
dtypes: float64(21), int64(13), object(7)
memory usage: 256.7+ KB

In [11]:
abilities_df = df['abilities']

In [12]:
abilities_df

0      ['Overgrow', 'Chlorophyll']
1      ['Overgrow', 'Chlorophyll']
2      ['Overgrow', 'Chlorophyll']
3         ['Blaze', 'Solar Power']
4         ['Blaze', 'Solar Power']
                  ...
796                ['Beast Boost']
797                ['Beast Boost']
798                ['Beast Boost']
799                ['Prism Armor']
800                 ['Soul-Heart']
Name: abilities, Length: 801, dtype: object

In [13]:
type(abilities_df)

pandas.core.series.Series

In [14]:
type(abilities_df[0])

str

In [15]:
abilities_df[0]

"['Overgrow', 'Chlorophyll']"

In [16]:
subset = df[['abilities', 'weight_kg', 'generation']]

In [17]:
subset

                       abilities  weight_kg  generation
0    ['Overgrow', 'Chlorophyll']        6.9           1
1    ['Overgrow', 'Chlorophyll']       13.0           1
2    ['Overgrow', 'Chlorophyll']      100.0           1
3       ['Blaze', 'Solar Power']        8.5           1
4       ['Blaze', 'Solar Power']       19.0           1
..                           ...        ...         ...
796              ['Beast Boost']      999.9           7
797              ['Beast Boost']        0.1           7
798              ['Beast Boost']      888.0           7
799              ['Prism Armor']      230.0           7
800               ['Soul-Heart']       80.5           7

[801 rows x 3 columns]

In [18]:
df.loc[0]

abilities            ['Overgrow', 'Chlorophyll']
against_bug                                    1
against_dark                                   1
against_dragon                                 1
against_electric                             0.5
against_fairy                                0.5
against_fight                                0.5
against_fire                                   2
against_flying                                 2
against_ghost                                  1
against_grass                               0.25
against_ground                                 1
against_ice                                    2
against_normal                                 1
against_poison                                 1
against_psychic                                2
against_rock                                   1
against_steel                                  1
against_water                                0.5
attack                                        49
base_egg_steps                              5120
base_happiness                                70
base_total                                   318
capture_rate                                  45
classfication                       Seed Pokémon
defense                                       49
experience_growth                        1059860
height_m                                     0.7
hp                                            45
japanese_name                   Fushigidaneフシギダネ
name                                   Bulbasaur
percentage_male                             88.1
pokedex_number                                 1
sp_attack                                     65
sp_defense                                    65
speed                                         45
type1                                      grass
type2                                     poison
weight_kg                                    6.9
generation                                     1
is_legendary                                   0
Name: 0, dtype: object

In [19]:
df[0]

KeyError: 0

In [ ]:
df.iloc[1]

In [ ]:
df.iloc[-1]

In [ ]:
df.loc[:, ['abilities', 'weight_kg', 'generation']]

In [ ]:
df.iloc[:10, [1, 30,40]]

In [ ]:
df.loc[:10, ['abilities', 'japanese_name']]

In [ ]:
df.iloc[:, 0:6]

In [ ]:
df.iloc[:, 0::2]

In [ ]:
df.iloc[:, :6:2]

In [ ]:
df.iloc[:, ::2]

In [ ]:
df.iloc[:, ::]

In [21]:
df.iloc[[0, 99], [0, 3, 5]]

                                abilities  against_dragon  against_fairy
0             ['Overgrow', 'Chlorophyll']             1.0            0.5
99  ['Soundproof', 'Static', 'Aftermath']             1.0            1.0

In [25]:
df[['japanese_name', 'speed']]

        japanese_name  speed
0    Fushigidaneフシギダネ     45
1     Fushigisouフシギソウ     60
2    Fushigibanaフシギバナ     80
3        Hitokageヒトカゲ     65
4         Lizardoリザード     80
..                ...    ...
796    Tekkaguyaテッカグヤ     61
797   Kamiturugiカミツルギ    109
798   Akuzikingアクジキング     43
799     Necrozmaネクロズマ     79
800      Magearnaマギアナ     65

[801 rows x 2 columns]